name: Citibike Feature Engineering Pipeline
on:
  schedule:
    - cron: '0 1 * * 3'  # Every Wednesday at 1:00 AM UTC
  workflow_dispatch:

jobs:
  feature_engineering:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install awscli
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
      
      - name: Create directories
        run: |
          mkdir -p data/{raw,processed,transformed}
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
      
      - name: Set environment variables
        run: |
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION || 'us-east-1' }}" >> $GITHUB_ENV
          echo "SAGEMAKER_ROLE_ARN=${{ secrets.SAGEMAKER_ROLE_ARN }}" >> $GITHUB_ENV
          echo "FEATURE_STORE_BUCKET=${{ secrets.FEATURE_STORE_BUCKET }}" >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      
      - name: Run Feature Engineering Pipeline
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          echo "Running feature engineering pipeline..."
          python src/pipelines/citibank_feature_pipeline.py \
            --year-start 2024 \
            --month-start 1 \
            --year-end 2025 \
            --month-end 1
      
      - name: Save feature files
        if: always()
        run: |
          mkdir -p artifacts
          
          if ls data/transformed/*.parquet 1> /dev/null 2>&1; then
            cp data/transformed/*.parquet artifacts/
            echo "Feature files copied to artifacts directory:"
            ls -la artifacts/
          else
            echo "No feature files were generated in this run" > artifacts/README.txt
            echo "No parquet files found"
          fi
          
          # Create a zip file of the artifacts
          zip -r feature-files.zip artifacts/
