name: Feature Store to S3 Migration
on:
  # Run weekly on Friday
  schedule:
    - cron: '0 4 * * 5'  # Every Friday at 4:00 AM UTC
  
  # Allow manual triggering
  workflow_dispatch:
  

jobs:
  migrate_feature_store:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install awscli
           if [ -f requirements.txt ]; then
             pip install -r requirements.txt
           fi
      
      
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
      
      - name: Set environment variables
        run: |
          echo "AWS_DEFAULT_REGION=${{ secrets.AWS_REGION || 'us-east-1' }}" >> $GITHUB_ENV
          echo "TARGET_S3_BUCKET=${{ secrets.TARGET_S3_BUCKET }}" >> $GITHUB_ENV
          echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
      
      - name: Run migration script
        run: |
          # Assuming the script is in src/pipelines/migration.py
          # If it's located elsewhere, adjust the path
          python src/pipelines/migration.py
